name: jisho_study_tool
description: A dictionary app for studying japanese
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  animated_size_and_fade: ^3.0.0
  auto_size_text: ^3.0.0
  collection: ^1.15.0
  confirm_dialog: ^1.0.0
  division: ^0.9.0
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_settings_ui: ^2.0.1
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.0.2
  get_it: ^7.2.0
  http: ^0.13.4
  just_audio: ^0.9.18
  mdi: ^5.0.0-nullsafety.0
  path: ^1.8.0
  path_provider: ^2.0.2
  ruby_text: ^3.0.1
  share_plus: ^6.3.1
  shared_preferences: ^2.0.6
  signature: ^5.0.0
  sqflite: ^2.0.2
  sqflite_common_ffi: ^2.1.1
  test: ^1.19.5
  unofficial_jisho_api: ^3.0.0
  # unofficial_jisho_api:
  #   path: /home/h7x4/git/unofficial-jisho-api-dart
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/components/
    - assets/images/links/
    - assets/images/logo/
    - assets/migrations/
    - assets/licenses/


  fonts:
    - family: Droid Sans Japanese
      fonts:
        - asset: assets/fonts/DroidSansJapanese.ttf

    - family: Noto Sans CJK
      fonts:
        - asset: assets/fonts/NotoSansCJK-Regular.ttc

    - family: Noto Serif CJK
      fonts:
        - asset: assets/fonts/NotoSerifCJK-Regular.ttc
        # - asset: fonts/Schyler-Italic.ttf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
