name: jisho_study_tool
description: A dictionary app for studying japanese
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_size_and_fade: ^3.0.0
  collection: ^1.15.0
  confirm_dialog: ^1.0.0
  division: ^0.9.0
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_settings_ui: ^2.0.1
  flutter_slidable: ^1.1.0
  flutter_svg: ^1.0.2
  get_it: ^7.2.0
  http: ^0.13.4
  just_audio: ^0.9.18
  mdi: ^5.0.0-nullsafety.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sembast: ^3.1.1
  share_plus: ^4.0.4
  test: ^1.19.5
  shared_preferences: ^2.0.6
  signature: ^5.0.0
  unofficial_jisho_api: ^2.0.4
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/components/
    - assets/images/links/
    - assets/images/logo/
    - assets/licenses/


  fonts:
    - family: Droid Sans Japanese
      fonts:
        - asset: assets/fonts/DroidSansJapanese.ttf

    - family: Noto Sans CJK
      fonts:
        - asset: assets/fonts/NotoSansCJK-Regular.ttc

    - family: Noto Serif CJK
      fonts:
        - asset: assets/fonts/NotoSerifCJK-Regular.ttc
        # - asset: fonts/Schyler-Italic.ttf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
