name: jisho_study_tool
description: A dictionary app for studying japanese
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_size_and_fade: ^3.0.0
  confirm_dialog: ^1.0.0
  division: ^0.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_slidable: ^1.1.0
  get_it: ^7.2.0
  http: ^0.13.4
  mdi: ^5.0.0-nullsafety.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sembast: ^3.1.1
  flutter_settings_ui: ^2.0.1
  shared_preferences: ^2.0.6
  signature: ^5.0.0
  unofficial_jisho_api: ^2.0.2
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/denshi_jisho_background_overlay.png
    - assets/images/logo/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
